server:
  port: 9999

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Duo?serverTimezone=UTC
    username: root
    password: 1234

mybatis:
  type-aliases-package: data.dto
  mapper-locations: /mapper/**/*.xml
