server:
  port: 9999

spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/Duo?serverTimezone=UTC
#    username: root
#    password: 1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n9jj0-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123

mybatis:
  type-aliases-package: data.dto
  mapper-locations: /mapper/**/*.xml
